import type { ComponentType, SVGProps } from 'react';

import type { IconKey } from '../content';
import {
  CloudIcon,
  CodeIcon,
  CompassIcon,
  DatabaseIcon,
  FlaskIcon,
  GlobeIcon,
  Heading1Icon,
  HourglassIcon,
  LayersIcon,
  LinkIcon,
  PaletteIcon,
  PinIcon,
  PlayCircleIcon,
  RouteIcon,
  SearchIcon,
  ServerIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SparklesIcon,
  TagIcon,
  TargetIcon,
  TriangleAlertIcon,
  TypeIcon,
  WorkflowIcon,
} from '../icons';

export const iconRegistry: Record<IconKey, ComponentType<SVGProps<SVGSVGElement>>> = {
  type: TypeIcon,
  tag: TagIcon,
  link: LinkIcon,
  code: CodeIcon,
  palette: PaletteIcon,
  globe: GlobeIcon,
  database: DatabaseIcon,
  workflow: WorkflowIcon,
  route: RouteIcon,
  compass: CompassIcon,
  search: SearchIcon,
  sparkles: SparklesIcon,
  cloud: CloudIcon,
  server: ServerIcon,
  'shield-alert': ShieldAlertIcon,
  'shield-check': ShieldCheckIcon,
  'triangle-alert': TriangleAlertIcon,
  pin: PinIcon,
  heading: Heading1Icon,
  hourglass: HourglassIcon,
  layers: LayersIcon,
  flask: FlaskIcon,
  'play-circle': PlayCircleIcon,
  target: TargetIcon,
};
