import type { ComponentType, SVGProps } from 'react';

import type { IconKey } from '../content';
import {
  AtomIcon,
  BoxesIcon,
  BoxIcon,
  CheckCircleIcon,
  CompassIcon,
  HourglassIcon,
  LayersIcon,
  LoaderIcon,
  MousePointerClickIcon,
  PauseCircleIcon,
  PlayCircleIcon,
  RotateCcwIcon,
  RouteIcon,
  SearchIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SplitIcon,
  TargetIcon,
  TriangleAlertIcon,
  WorkflowIcon,
  XCircleIcon,
} from '../icons';

export const iconRegistry: Record<IconKey, ComponentType<SVGProps<SVGSVGElement>>> = {
  hourglass: HourglassIcon,
  loader: LoaderIcon,
  check: CheckCircleIcon,
  'x-circle': XCircleIcon,
  'triangle-alert': TriangleAlertIcon,
  sparkles: SparklesIcon,
  'shield-check': ShieldCheckIcon,
  'shield-alert': ShieldAlertIcon,
  route: RouteIcon,
  workflow: WorkflowIcon,
  box: BoxIcon,
  boxes: BoxesIcon,
  search: SearchIcon,
  split: SplitIcon,
  atom: AtomIcon,
  compass: CompassIcon,
  'mouse-click': MousePointerClickIcon,
  'play-circle': PlayCircleIcon,
  'pause-circle': PauseCircleIcon,
  layers: LayersIcon,
  rotate: RotateCcwIcon,
  target: TargetIcon,
};
