import {
  ArrowRight,
  Atom,
  Box,
  Boxes,
  CheckCircle2,
  ClipboardCheck,
  Clock,
  Code,
  Database,
  Droplet,
  ExternalLink,
  FileCode,
  FileText,
  GitBranch,
  HelpCircle,
  Layers,
  Monitor,
  MousePointer,
  Network,
  Scale,
  Search,
  Star,
} from 'lucide-react';
import type { ComponentType, SVGProps } from 'react';

import type { DvcIconName } from './content';

export {
  ArrowRight as ArrowRightIcon,
  BookOpen as BookOpenIcon,
  CheckCircle2 as CheckCircleIcon,
  ChevronRight as ChevronRightIcon,
  ClipboardCheck as ClipboardCheckIcon,
  Code2 as CodeIcon,
  ExternalLink as ExternalLinkIcon,
  HelpCircle as HelpCircleIcon,
  Info as InfoIcon,
  Lightbulb as LightbulbIcon,
  Map as MapIcon,
  PlayCircle as PlayCircleIcon,
  RotateCcw as RotateIcon,
  Scale as ScaleIcon,
  Sparkles as SparklesIcon,
  Star as StarIcon,
  XCircle as XCircleIcon,
} from 'lucide-react';

type LucideLike = ComponentType<SVGProps<SVGSVGElement>>;

export const dvcIcon: Record<DvcIconName, LucideLike> = {
  arrowRight: ArrowRight,
  atom: Atom,
  box: Box,
  check: CheckCircle2,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  code: Code,
  cube: Boxes,
  cursor: MousePointer,
  database: Database,
  droplet: Droplet,
  externalLink: ExternalLink,
  fileCode: FileCode,
  fileText: FileText,
  gitBranch: GitBranch,
  help: HelpCircle,
  layers: Layers,
  monitor: Monitor,
  network: Network,
  scale: Scale,
  search: Search,
  star: Star,
};
