packages:
  - "apps/*"
  - "packages/*"
  - "tools/**"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  less: false
  nx: true
  sharp: true
  unrs-resolver: true

autoInstallPeers: true

minimumReleaseAgeExclude:
  - "@berrypjh/tsconfig@1.1.0"
  - "@berrypjh/react-ui@1.1.0 || 1.1.1"
  - "@berrypjh/commitlint-config@1.1.0"
  - "@berrypjh/eslint-config@1.1.0"
  - "@berrypjh/prettier-config@1.1.0"
