import type { ComponentType, SVGProps } from 'react';

import type { IconKey } from '../content';
import {
  BracesIcon,
  CloudIcon,
  CompassIcon,
  DatabaseIcon,
  FolderIcon,
  GlobeIcon,
  HammerIcon,
  HardDriveIcon,
  LayersIcon,
  MonitorIcon,
  MousePointerClickIcon,
  NetworkIcon,
  PackageIcon,
  PlayCircleIcon,
  PlugIcon,
  RouteIcon,
  SearchIcon,
  ServerIcon,
  SettingsIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SplitIcon,
  TargetIcon,
  WorkflowIcon,
} from '../icons';

export const iconRegistry: Record<IconKey, ComponentType<SVGProps<SVGSVGElement>>> = {
  server: ServerIcon,
  monitor: MonitorIcon,
  braces: BracesIcon,
  database: DatabaseIcon,
  package: PackageIcon,
  workflow: WorkflowIcon,
  route: RouteIcon,
  compass: CompassIcon,
  search: SearchIcon,
  sparkles: SparklesIcon,
  cloud: CloudIcon,
  'shield-check': ShieldCheckIcon,
  'mouse-click': MousePointerClickIcon,
  'play-circle': PlayCircleIcon,
  globe: GlobeIcon,
  split: SplitIcon,
  plug: PlugIcon,
  hammer: HammerIcon,
  settings: SettingsIcon,
  network: NetworkIcon,
  'hard-drive': HardDriveIcon,
  folder: FolderIcon,
  target: TargetIcon,
  layers: LayersIcon,
};
