import type { ComponentType, SVGProps } from 'react';

import type { IconKey } from '../content';
import {
  BoxesIcon,
  BoxIcon,
  BrushIcon,
  CheckCircleIcon,
  CompassIcon,
  DatabaseIcon,
  EyeIcon,
  EyeOffIcon,
  GaugeIcon,
  LayersIcon,
  MousePointerClickIcon,
  PauseCircleIcon,
  PlayCircleIcon,
  RotateCcwIcon,
  RouteIcon,
  SearchIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SplitIcon,
  TargetIcon,
  TimerIcon,
  WorkflowIcon,
  XCircleIcon,
  ZapIcon,
} from '../icons';

export const iconRegistry: Record<IconKey, ComponentType<SVGProps<SVGSVGElement>>> = {
  eye: EyeIcon,
  'eye-off': EyeOffIcon,
  pause: PauseCircleIcon,
  play: PlayCircleIcon,
  gauge: GaugeIcon,
  brush: BrushIcon,
  timer: TimerIcon,
  sparkles: SparklesIcon,
  rotate: RotateCcwIcon,
  workflow: WorkflowIcon,
  split: SplitIcon,
  route: RouteIcon,
  compass: CompassIcon,
  search: SearchIcon,
  check: CheckCircleIcon,
  'x-circle': XCircleIcon,
  'shield-check': ShieldCheckIcon,
  layers: LayersIcon,
  database: DatabaseIcon,
  box: BoxIcon,
  boxes: BoxesIcon,
  zap: ZapIcon,
  'mouse-click': MousePointerClickIcon,
  target: TargetIcon,
};
