import type { ComponentType, SVGProps } from 'react';

import type { IconKey } from '../content';
import {
  ActivityIcon,
  BarChart3Icon,
  BookOpenIcon,
  CheckCircleIcon,
  CompassIcon,
  DatabaseIcon,
  GaugeIcon,
  GitCommitIcon,
  GlobeIcon,
  HashIcon,
  HourglassIcon,
  LayersIcon,
  MilestoneIcon,
  NewspaperIcon,
  PlayCircleIcon,
  RefreshCcwIcon,
  RouteIcon,
  SearchIcon,
  ServerIcon,
  ShieldCheckIcon,
  SparklesIcon,
  TagIcon,
  TargetIcon,
  TimerIcon,
  WavesIcon,
  WorkflowIcon,
} from '../icons';

export const iconRegistry: Record<IconKey, ComponentType<SVGProps<SVGSVGElement>>> = {
  database: DatabaseIcon,
  layers: LayersIcon,
  workflow: WorkflowIcon,
  gauge: GaugeIcon,
  route: RouteIcon,
  compass: CompassIcon,
  sparkles: SparklesIcon,
  server: ServerIcon,
  chart: BarChart3Icon,
  waves: WavesIcon,
  hash: HashIcon,
  globe: GlobeIcon,
  tag: TagIcon,
  newspaper: NewspaperIcon,
  milestone: MilestoneIcon,
  'git-commit': GitCommitIcon,
  search: SearchIcon,
  'shield-check': ShieldCheckIcon,
  target: TargetIcon,
  check: CheckCircleIcon,
  timer: TimerIcon,
  'play-circle': PlayCircleIcon,
  hourglass: HourglassIcon,
  refresh: RefreshCcwIcon,
  activity: ActivityIcon,
  book: BookOpenIcon,
};
