import type { ComponentType, SVGProps } from 'react';

import type { IconKey } from '../content';
import {
  BanIcon,
  BellRingIcon,
  CheckCircleIcon,
  CompassIcon,
  LayersIcon,
  NetworkIcon,
  PaletteIcon,
  PlugIcon,
  PlugZapIcon,
  RefreshCcwIcon,
  RouteIcon,
  SearchIcon,
  SettingsIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SplitIcon,
  TargetIcon,
  TimerIcon,
  UnplugIcon,
  WorkflowIcon,
  XIcon,
  ZapIcon,
} from '../icons';

export const iconRegistry: Record<IconKey, ComponentType<SVGProps<SVGSVGElement>>> = {
  plug: PlugIcon,
  'plug-zap': PlugZapIcon,
  unplug: UnplugIcon,
  refresh: RefreshCcwIcon,
  zap: ZapIcon,
  palette: PaletteIcon,
  bell: BellRingIcon,
  split: SplitIcon,
  sparkles: SparklesIcon,
  'shield-alert': ShieldAlertIcon,
  'shield-check': ShieldCheckIcon,
  route: RouteIcon,
  compass: CompassIcon,
  search: SearchIcon,
  workflow: WorkflowIcon,
  settings: SettingsIcon,
  timer: TimerIcon,
  check: CheckCircleIcon,
  x: XIcon,
  ban: BanIcon,
  globe: SparklesIcon,
  network: NetworkIcon,
  target: TargetIcon,
  layers: LayersIcon,
};
