import './global.css';
import { getServerTheme, getServerLocale } from '@it-tech-blog/preferences/server';
import { ThemeProvider, LocaleProvider } from '@it-tech-blog/preferences';

export const metadata = {
  title: 'Welcome to accessibility-zone',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [theme, locale] = await Promise.all([getServerTheme(), getServerLocale()]);

  return (
    <html lang={locale} className={theme}>
      <body>
        <ThemeProvider defaultTheme={theme}>
          <LocaleProvider defaultLocale={locale}>{children}</LocaleProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
