import {
  ArrowRight,
  Atom,
  Box,
  Boxes,
  CheckCircle2,
  Clock,
  Code,
  Compass,
  Database,
  FileCode,
  GitBranch,
  HelpCircle,
  Layers,
  ListChecks,
  Map as MapPin,
  Monitor,
  Network,
  Share2,
  Shield,
  Sparkles,
  Star,
  Workflow,
} from 'lucide-react';
import type { ComponentType, SVGProps } from 'react';

import type { PdIconName } from './content';

export {
  ArrowRight as ArrowRightIcon,
  BookOpen as BookOpenIcon,
  CheckCircle2 as CheckCircleIcon,
  ChevronRight as ChevronRightIcon,
  Code2 as CodeIcon,
  ExternalLink as ExternalLinkIcon,
  HelpCircle as HelpCircleIcon,
  Info as InfoIcon,
  Lightbulb as LightbulbIcon,
  ListChecks as ListChecksIcon,
  Map as MapIcon,
  PlayCircle as PlayCircleIcon,
  RotateCcw as RotateIcon,
  Sparkles as SparklesIcon,
  Square as SquareIcon,
  Star as StarIcon,
  XCircle as XCircleIcon,
} from 'lucide-react';

type LucideLike = ComponentType<SVGProps<SVGSVGElement>>;

export const pdIcon: Record<PdIconName, LucideLike> = {
  arrowRight: ArrowRight,
  atom: Atom,
  box: Box,
  check: CheckCircle2,
  checkList: ListChecks,
  clock: Clock,
  code: Code,
  compass: Compass,
  cube: Boxes,
  database: Database,
  fileCode: FileCode,
  gitBranch: GitBranch,
  help: HelpCircle,
  layers: Layers,
  map: MapPin,
  monitor: Monitor,
  network: Network,
  share: Share2,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  workflow: Workflow,
};
